# Generated by Django 3.0.14 on 2022-03-23 21:14

from django.db import migrations, models
import django.db.models.deletion
import mhd.utils.uuid
import mhd_data.fields.ndarray


class Migration(migrations.Migration):

    dependencies = [
        ('mhd_provenance', '0001_initial'),
        ('mhd_schema', '0008_auto_20200323_1241'),
        ('mhd_data', '0002_auto_20191029_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorizationAsSparseArray',
            fields=[
                ('id', models.UUIDField(default=mhd.utils.uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Is this item active')),
                ('value', mhd_data.fields.ndarray.SmartNDArrayField(dim=1, size=None, typ=models.IntegerField())),
                ('item', models.ForeignKey(help_text='Item this this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mhd_data.Item')),
                ('prop', models.ForeignKey(help_text='Property this cell represents', on_delete=django.db.models.deletion.CASCADE, to='mhd_schema.Property')),
                ('provenance', models.ForeignKey(help_text='Provenance of this cell', on_delete=django.db.models.deletion.CASCADE, to='mhd_provenance.Provenance')),
                ('superseeded_by', models.ForeignKey(blank=True, help_text='Cell this value is superseeded by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mhd_data.FactorizationAsSparseArray')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='factorizationassparsearray',
            index=models.Index(fields=['item'], name='mhd_data_fa_item_id_1aede0_idx'),
        ),
        migrations.AddIndex(
            model_name='factorizationassparsearray',
            index=models.Index(fields=['prop'], name='mhd_data_fa_prop_id_bdd593_idx'),
        ),
        migrations.AddIndex(
            model_name='factorizationassparsearray',
            index=models.Index(fields=['active'], name='mhd_data_fa_active_774136_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factorizationassparsearray',
            unique_together={('item', 'prop', 'superseeded_by')},
        ),
    ]
