version: '3'

services:
  postgresdb:
    container_name: math_data_db
    image: postgres:14
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    # volumes:
    #   - ./db-data-db/:/var/lib/postgresql/data
    shm_size: 2G

  feserver:
    container_name: math_data_fe
    build:
      context: ../../
      dockerfile:
        docker/local/Frontend.Dockerfile
    ports:
      - "0.0.0.0:6543:3000"
    depends_on:
      - mhd-appserver
    volumes:
      - ../../frontend/src:/app/frontend/src
      - ../../frontend/.env:/app/frontend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mhd-production-server:
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY_BASE=${DJANGO_SECRET_KEY}
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DB_ENGINE: "django.db.backends.postgresql"
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_DB_HOST: math_data_db
      DJANGO_DB_PORT: 5432

    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - postgresdb

  mhd-appserver:
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    container_name: math_data_app
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_DB_ENGINE: "django.db.backends.postgresql"
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_DB_HOST: math_data_db
      DJANGO_DB_PORT: 5432
    ports:
      - "0.0.0.0:8080:8000"
    depends_on:
      - postgresdb
    volumes:
      - ../../:/app
